### ISSUE TITLE
Not able to get it to work.

### ISSUE THREAD

**Issue by paaljoachim** [closemarketing/duplicate-publish-multisite#1]
Hey @davidperezgar 

I am updating a tutorial I have on various multisite plugins. I found your plugin interesting and I am trying it out.

I downloaded and uploaded the plugin from this Github repo.
Network activated it.
Added the same category: News and Multi to primary site and two sub sites.

In sub site sunwindcreation.com
Went to a sub site and Settings -> Publish Multisite.
Category from load: Multi
Site to publish: My Testing Box (primary site)
Category to publish: Multi
Author: joachim

In sub site bluewinddesign.com
Category from load: Multi
Site to publish: My Testing Box (primary site)
Category to publish: Multi
Author: joachim

In primary site mytestingbox.com
Category from load: Multi
Site to publish: -
Category to publish: Multi
Author: joachim

I expected that I could go to https://mytestingbox.com/blog/ and see the blog posts from sunwindcreation.com and bluewinddesign.com but was not able to do so. It seems I might be missing a step.

**Comment by davidperezgar** [comment]
Hello! did you use from the official repository?
https://wordpress.org/plugins/duplicate-publish-multisite/

If you use debug.log activated, you could see the logs and see where is the problem...

**Comment by paaljoachim** [comment]
Hey David.

I think I am getting it to work. It is just some confusion around how it work.
Thanks!

**Comment by davidperezgar** [comment]
Ok!
